import io
import subprocess
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from unittest.mock import patch

from bobp.tools import _bob_manage


def _install(target: Path, **kwargs) -> None:
    """install() with the real (global-state-touching) skill-link setup mocked out."""
    with patch.object(_bob_manage, "_run_setup_agent_links"):
        _bob_manage.install(target, **kwargs)


class InstallTests(unittest.TestCase):
    def test_install_creates_real_skill_files_and_blank_state(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            _install(target)

            self.assertTrue((target / "agents" / "bob.docs" / "SKILL.md").is_file())
            self.assertFalse((target / "agents" / "bob.docs" / "SKILL.md.txt").exists())
            self.assertFalse(list((target / "agents").rglob("*.txt")))

            chat = (target / "agents" / "CHAT.md").read_text()
            self.assertIn("Chat Message Template", chat)

            lessons = (target / "agents" / "oracle.docs" / "lessons.md").read_text()
            self.assertNotIn("2026-05-06", lessons)  # no leaked project-specific history

            self.assertFalse((target / "agents" / "PROJECT.md").exists())  # generated by setup, not shipped

    def test_install_does_not_touch_the_target_projects_makefile(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            _install(target)
            self.assertFalse((target / "Makefile").exists())

    def test_install_refuses_to_clobber_an_existing_install(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            _install(target)
            (target / "agents" / "CHAT.md").write_text("real history, do not destroy\n")

            with self.assertRaises(SystemExit):
                _install(target)

            self.assertEqual(
                (target / "agents" / "CHAT.md").read_text(), "real history, do not destroy\n"
            )

    def test_install_force_overwrites_an_existing_install(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            _install(target)
            (target / "agents" / "CHAT.md").write_text("will be overwritten\n")

            _install(target, force=True)

            self.assertIn("Chat Message Template", (target / "agents" / "CHAT.md").read_text())

    def test_install_errors_on_missing_target(self):
        with self.assertRaises(SystemExit):
            _install(Path("/nonexistent/definitely/not/a/real/path"))


class UpdateTests(unittest.TestCase):
    def test_update_refreshes_skills_but_preserves_state_and_chat(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            _install(target)

            # Simulate real accumulated project history since the install.
            state_file = target / "agents" / "neo.docs" / "state.md"
            state_file.write_text("## Current Task\nreal in-progress work\n")
            chat_file = target / "agents" / "CHAT.md"
            chat_file.write_text("real chat history\n")
            skill_file = target / "agents" / "neo.docs" / "SKILL.md"
            skill_file.write_text("stale persona content from an older bobp version\n")

            with patch.object(_bob_manage, "_run_setup_agent_links"):
                _bob_manage.update(target)

            self.assertEqual(state_file.read_text(), "## Current Task\nreal in-progress work\n")
            self.assertEqual(chat_file.read_text(), "real chat history\n")
            self.assertIn("Senior Software Engineer", skill_file.read_text())  # refreshed from template
            self.assertTrue((target / "agents" / "skills" / "make" / "SKILL.md").is_file())
            self.assertFalse(list((target / "agents").rglob("*.txt")))

    def test_update_initialises_state_when_missing(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            _install(target)
            state_file = target / "agents" / "neo.docs" / "state.md"
            state_file.unlink()

            with patch.object(_bob_manage, "_run_setup_agent_links"):
                _bob_manage.update(target)

            self.assertTrue(state_file.exists())


class PullTests(unittest.TestCase):
    def test_pull_copies_only_files_already_present_at_destination(self):
        with tempfile.TemporaryDirectory() as src_tmp, tempfile.TemporaryDirectory() as dst_tmp:
            src, dst = Path(src_tmp), Path(dst_tmp)
            _install(src)
            _install(dst)

            (src / "agents" / "neo.docs" / "SKILL.md").write_text("updated persona text\n")
            new_file = src / "agents" / "skills" / "chat" / "brand_new_file.md"
            new_file.write_text("should not be pulled in\n")

            with patch.object(_bob_manage, "find_project_root", return_value=dst):
                _bob_manage.pull(src)

            self.assertEqual(
                (dst / "agents" / "neo.docs" / "SKILL.md").read_text(), "updated persona text\n"
            )
            self.assertFalse((dst / "agents" / "skills" / "chat" / "brand_new_file.md").exists())


class CleanTests(unittest.TestCase):
    def test_clean_resets_state_and_chat_to_templates(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            _install(target)
            (target / "agents" / "neo.docs" / "state.md").write_text("real work in progress\n")
            (target / "agents" / "CHAT.md").write_text("real chat history\n")

            with patch("subprocess.run") as run:
                with patch.object(_bob_manage, "find_project_root", return_value=target):
                    _bob_manage.clean()
                run.assert_called_once()

            self.assertIn(
                "Not started", (target / "agents" / "neo.docs" / "state.md").read_text()
            )
            self.assertIn(
                "Chat Message Template", (target / "agents" / "CHAT.md").read_text()
            )


class DiffTests(unittest.TestCase):
    def test_diff_reports_modified_and_missing_files(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            _install(target)
            (target / "agents" / "neo.docs" / "SKILL.md").write_text("locally modified\n")
            import shutil

            shutil.rmtree(target / "agents" / "templates")

            buf = io.StringIO()
            with redirect_stdout(buf):
                _bob_manage.diff(target)

            output = buf.getvalue()
            self.assertIn("Files differ: agents/neo.docs/SKILL.md", output)
            self.assertIn("Only in template: agents/templates/", output)


class InstallCliIntegrationTests(unittest.TestCase):
    """Runs the real `bobp install` CLI end-to-end (no mocking) to catch wiring
    bugs the unit tests above can't see: argparse plumbing, module dispatch,
    the templates_dir()/import bobp path lookup. setup_agent_links' via/codex
    steps degrade to no-ops when those binaries aren't on PATH, so this stays
    safe to run in CI."""

    def test_install_via_the_real_cli(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = subprocess.run(
                [sys.executable, "-m", "bobp.cli", "install", str(target)],
                capture_output=True, text=True,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertTrue((target / "agents" / "bob.docs" / "SKILL.md").is_file())


if __name__ == "__main__":
    unittest.main()
